### ISSUE TITLE
Add support for $ref references to model classes

### ISSUE THREAD

**Issue by petrdvorak** [robertlove/jekyll-openapi#1]
We have large automatically generated Swagger files that contain references to model classes, rather than embedding the model classes directly, for example:

```json
"responses": {
    "200": {
        "description": "OK",
        "schema": {
            "$ref": "#/definitions/PetResponse"
        }
    },
}
```

We would like these references to be rendered as if the model classes were present directly.

**Comment by robertlove** [comment]
Hi @petrdvorak. Thanks for reminding me about this project. It's been a long time. The project is open source and contributions are more than welcome so please feel free to submit any changes via a pull request. The change you're suggesting is definitely needed. Thanks!

**Comment by waldyrious** [comment]
@robertlove in the spirit of the excellent README and CONTRIBUTING documentation that this project uses, I thought I'd confirm with you that the reason you closed this issue is that the project already supports resolving `$ref`s — is that right? At least in my experiments, these seem to work for references within the same file. References to other files aren't followed, though, so maybe that's what @petrdvorak was asking for?
